# Generated by Django 3.1 on 2021-05-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrefvalue', models.CharField(max_length=400)),
                ('linkname', models.CharField(max_length=60)),
            ],
        ),
    ]
